name: 使用PyInstaller进行跨平台构建

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.7  # 配置你所需的Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build Executable
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          pyinstaller --onefile --windowed -i icon.ico GUI.py
          # 或者指定更复杂的配置文件和选项
        elif [ "$RUNNER_OS" == "Linux" ]; then
          pyinstaller --onefile --windowed -i icon.ico GUI.py
        elif [ "$RUNNER_OS" == "macOS" ]; then
          pyinstaller --onefile --windowed -i icon.ico GUI.py
        fi

    - name: Upload all platform artifacts together
      uses: actions/upload-artifact@v2
      with:
        name: app-all-platforms
        path: |
          dist/*.exe
          dist/*.AppImage
          dist/*.app

# 如果需要，还可以添加步骤将构建好的可执行文件发布到其他位置或者创建GitHub Release等
