name: 自动化GUI构建

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.7'  # 指定Python版本

    - name: Install PyInstaller
      run: pip install pyinstaller

    #- name: Build for Linux
     # run: |
      #  pyinstaller -i icon.ico -w GUI.py
       # mv dist/cczuical .

    - name: Build for Windows
      run: |
        pyinstaller -i icon.ico -w GUI.py
        mv dist/cczuical.exe .

    - name: Build for macOS
      run: |
        pyinstaller -i icon.ico -w GUI.py
        mv dist/cczuical.app .

