name: 发布可执行文件

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: 发布可执行文件
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 代码
      uses: actions/checkout@v2
      
    - name: 下载 artifact
      uses: actions/download-artifact@v2
      with:
        name: app-${{ matrix.os }}.*

    - name: 创建 Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: 上传可执行文件
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app-${{ matrix.os }}.*
        asset_name: app-${{ matrix.os }}.*
        asset_content_type: application/octet-stream
