name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract tag version
      id: extract_version
      run: echo ::set-output name=tag_version::${GITHUB_REF#refs/tags/}

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.repository.releases[0].upload_url }}
        asset_path: dist/*
        asset_name: app-${{ steps.extract_version.outputs.tag_version }}-${{ matrix.os }}.zip
        asset_content_type: application/zip
        token: ${{ secrets.GITHUB_TOKEN }}
