name: 构建和发布

on:
  push:
    branches:
      - main

jobs:
  build:
    name: PyInstaller构建
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.11.7]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: 安装依赖
      run: |
        pip install -r requirements.txt
    
    - name: 安装PyInstaller
      run: |
        pip install pyinstaller
    
    - name: Build with PyInstaller
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          pyinstaller --onefile --windowed -i icon.ico GUI.py
        elif [ "$RUNNER_OS" == "Linux" ]; then
          pyinstaller --onefile --windowed -i icon.ico GUI.py
        elif [ "$RUNNER_OS" == "macOS" ]; then
          pyinstaller --onefile --windowed -i icon.icns GUI.py
        fi
      shell: bash
    
    - name: 上传 Windows 工程
      uses: actions/upload-artifact@v2
      if: startsWith(matrix.os, 'windows')
      with:
        name: app-${{ matrix.os }}.exe
        path: dist/*.exe
    
    - name: 上传 Linux 工程
      uses: actions/upload-artifact@v2
      if: startsWith(matrix.os, 'ubuntu') # GitHub Actions uses 'ubuntu-latest' for Linux
      with:
        name: app-${{ matrix.os }}.AppImage
        path: dist/*.AppImage
    
    - name: 上传 macOS 工程
      uses: actions/upload-artifact@v2
      if: startsWith(matrix.os, 'macos')
      with:
        name: app-${{ matrix.os }}.app
        path: dist/*.app    

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # 添加此步骤以设置Git用户信息
    - name: Set Git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    # 添加自定义版本号生成逻辑
    - name: Checkout code (用于创建新标签)
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # 确保获取所有历史记录以找到最新的标签

    - name: Get Latest Tag
      id: get_latest_tag
      run: |
        LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "::set-output name=latest_tag::$LATEST_TAG"

    - name: Parse and Increment Version
      id: increment_version
      run: |
        MAJOR=$(echo ${{ steps.get_latest_tag.outputs.latest_tag }} | cut -d'.' -f1 | sed 's/v//')
        MINOR=$(echo ${{ steps.get_latest_tag.outputs.latest_tag }} | cut -d'.' -f2)
        PATCH=$(echo ${{ steps.get_latest_tag.outputs.latest_tag }} | cut -d'.' -f3)

        ((PATCH++))

        if [ $PATCH -ge 10 ]; then
          ((MINOR++))
          PATCH=1
        fi

        NEW_VERSION=v$MAJOR.$MINOR.$PATCH
        echo "NEW_VERSION=$NEW_VERSION"
        echo "::set-output name=new_version::$NEW_VERSION"

    - name: Create New Tag
      run: |
        git tag -a ${{ steps.increment_version.outputs.new_version }} -m "Automatic release from main branch"
        git push origin ${{ steps.increment_version.outputs.new_version }}

    # 下载构建产物并上传至Release
    - name: Download Build Artifacts
      uses: actions/download-artifact@v2
      with:
        path: dist

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        tag_name: ${{ steps.increment_version.outputs.new_version }}
        release_name: Release ${{ steps.increment_version.outputs.new_version }}
        draft: false
        prerelease: false

    - name: 上传 Windows 工程到Release
      if: matrix.os == 'windows-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/app-windows-latest.exe
        asset_name: cczuical-windows-latest.exe
        asset_content_type: application/octet-stream

    - name: 上传 Linux 工程到Release
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/app-ubuntu-latest.AppImage
        asset_name: cczuical-ubuntu-latest.AppImage
        asset_content_type: application/octet-stream

    - name: 上传 macOS 工程到Release
      if: matrix.os == 'macos-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/app-macos-latest.app/ # 注意：macOS应用通常是一个目录，而非单个文件
        asset_name: cczuical-macos-latest.zip # 将整个.app目录压缩为zip文件再上传
        asset_content_type: application/zip

# 在构建阶段，需要确保产出的文件名与上面upload步骤中的asset_path相对应
